### ISSUE TITLE
Feature request filed

### ISSUE THREAD

**Issue by jbliesener** [waynepiekarski/XTextureExtractor#15]
I just filed a feature request to provide texture information through the X-Plane SDK:

https://feedback.x-plane.com/posts/402/documented-access-to-rendered-textures

I also provided another one for an external texture rendering engine that would run on a Raspberry Pi or other devices and that would be able to recreate the panel content just by accessing the datarefs and resource files. This would significantly relieve network and CPU load on X-Plane's host computer:

https://feedback.x-plane.com/posts/403/external-panel-texture-rendering-engine

Maybe you want to upvote these feature requests...

**Comment by waynepiekarski** [comment]
With XTE v3.x I have finally worked out a stable algorithm that works on both OpenGL and Vulkan, on Windows/Linux/Mac, and also works on both X-Plane 11 and 12. So while this feature request would always be handy to improve stability in the future, or get more access to other textures, for now we are good to go and XTE works fine for everyone.
