### ISSUE TITLE
Extracting texture wrong

### ISSUE THREAD

**Issue by simsekahmett** [waynepiekarski/XTextureExtractor#17]
Hello,

I was using XTextureExtractor with Zibo738 fine, from one time it started to extract textures wrong.

![image](https://user-images.githubusercontent.com/20887939/109546406-3628c480-7adb-11eb-8add-a7284b051c1a.png)

Log.txt;
```
XTextureExtractor2: Found ZiboMod 738 or Ultimate 739 based on acf_tailnum [zb738], changing file name to [zibo-b738.acf]
XTextureExtractor2: Loading XTextureExtractor state from C:\Program Files (x86)\Steam\steamapps\common\X-Plane 11\Resources\plugins\Plugin-XTextureExtractor-x64-Release\64\..\\zibo-b738.acf.tex
XTextureExtractor2: Read in [ZB738] = max(2048,2048) format(32856)
XTextureExtractor2: Read in 0 = [ND] LBRT=524, 1550, 1018, 2038
XTextureExtractor2: Read in 1 = [HSI] LBRT=9, 1538, 516, 2043
XTextureExtractor2: Read in 2 = [EICAS] LBRT=1040, 1550, 1527, 2028
XTextureExtractor2: Read in 3 = [EICAS-2] LBRT=1533, 1551, 2038, 2037
XTextureExtractor2: Read in 4 = [TABLET] LBRT=1156, 12, 2027, 611
XTextureExtractor2: Skipping line [# Alternate config with co-pilot displays
]
XTextureExtractor2: Skipping line [# ND-CP           524 1550 1018 2038
]
XTextureExtractor2: Skipping line [# PFD-CP            9 1538  516 2043
]
XTextureExtractor2: Skipping line [# EICAS          1040 1550 1527 2028
]
XTextureExtractor2: Skipping line [# MFD            1533 1551 2038 2037
]
XTextureExtractor2: Skipping line [# ND-FO           524 1025 1018 1530
]
XTextureExtractor2: Skipping line [# PFD-FO            9 1025  516 1530
]
XTextureExtractor2: Skipping line [# CDU-CP            9  550  540 1023
]
XTextureExtractor2: Skipping line [# CDU-FO          558  550 1200 1023
]
XTextureExtractor2: Skipping line [# STBY-HOR       1029 1025 1325 1310
]
XTextureExtractor2: Skipping line [# HUD               9    0  910  532
]
XTextureExtractor2: Skipping line [# STBY-ND-CP      524 1550 1018 2038
]
XTextureExtractor2: fgets returned NULL, finished reading with 5 successful textures
XTextureExtractor2: Could not load from file windowcockpit-ZB738.txt
XTextureExtractor2: Detected aircraft dirty flag set, so finding texture
XTextureExtractor2: Scheduling texture scan on next rendering pass
XTextureExtractor2: Candidate texture id = 1210
XTextureExtractor2: Candidate texture id = 347
XTextureExtractor2: Found panel texture id +1 = 348
XTextureExtractor2: Error! Mismatch texture id=348, width=8!=2048, height=1!=2048, internal format=33779!=32856
```

Any suggestions ?

**Comment by waynepiekarski** [comment]
Can you tell me a bit more about your system? What GPU are you using?

Are you using OpenGL or Vulkan? Which X-Plane version?

Did anything change or get updated since it worked last?

It looks like you are using XTE v2, so note that it doesn't work with Vulkan.

You could try using XTE v1.3 which used a manual texture algorithm and see if that works.

**Comment by simsekahmett** [comment]
Macbook Pro with Bootcamp Win10.

CPU: i7-6820 HQ
GPU: AMD Radeon Pro 460
XPlane: 11 (Steam)
Vulkan or OpenGL: How to find which one is in use ?
Yes i was using XTEv2.

Let me try with XTE v1.3.

________________________________
Gönderen: Wayne Piekarski <notifications@github.com>
Gönderildi: 1 Mart 2021 Pazartesi 22:28
Kime: waynepiekarski/XTextureExtractor <XTextureExtractor@noreply.github.com>
Bilgi: Ahmet Burhan Simsek <ahmet-simsek@hotmail.com>; Author <author@noreply.github.com>
Konu: Re: [waynepiekarski/XTextureExtractor] Extracting texture wrong (#17)


Can you tell me a bit more about your system? What GPU are you using?

Are you using OpenGL or Vulkan? Which X-Plane version?

Did anything change or get updated since it worked last?

It looks like you are using XTE v2, so note that it doesn't work with Vulkan.

You could try using XTE v1.3 which used a manual texture algorithm and see if that works.

**Comment by waynepiekarski** [comment]
I have never tested on an AMD Radeon before, and the auto texture algorithm relies on undocumented features to work. So if the driver changed, that could have an effect.

Did you download a new Zibo or get an X-Plane update via Steam recently?

There is a checkbox which selects Vulkan vs OpenGL support, here is a video that shows how to select it: https://www.youtube.com/watch?v=IGS70VVKvhA

**Comment by simsekahmett** [comment]
It seems Vulkan is not supported on my machine. 
I remember i did some tweaks from zibo side to increase FPS via changing object files in zibo folder.

https://forums.x-plane.org/index.php?/forums/topic/214404-extreme-low-res-texture-pack-for-zibo-737-800/

**Comment by simsekahmett** [comment]
How to use XTE v1.3?

**Comment by simsekahmett** [comment]
> How to use XTE v1.3?

Figured out that v1.3 exists as branch. I tested with v1.3 seems okay so far.

Thanks.

**Comment by waynepiekarski** [comment]
Since you don't have Vulkan support, that means you could use either XTE v2 or v1.3. However, there might be something about your video card, driver, etc that is causing the problem. v1.3 has a manual technique you can use to find the texture yourself by pressing the << button and cycling through the textures. This should work.

All versions of XTE can be downloaded here: https://github.com/waynepiekarski/XTextureExtractor/tree/master/Uploads
