### ISSUE TITLE
XP1000 Support

### ISSUE THREAD

**Issue by NetoSimoes** [waynepiekarski/XTextureExtractor#20]
Hello,
I hope you are well,

Thank you for your dedication in this project!

Are you planning to implement X-Plane1000 screens into this plugin?

Much appreciated,
Rodrigo

**Comment by waynepiekarski** [comment]
Can you give me more information on what an X-Plane1000 screen is? I'm not sure what you are referring to.

**Comment by airfightergr** [comment]
Probably is about X-Plane's G1000, cockpit devices.

**Comment by NetoSimoes** [comment]
![image](https://user-images.githubusercontent.com/67044705/223097761-d0e4ec25-51fc-4559-9d52-d9199138bd86.png)

**Comment by waynepiekarski** [comment]
Ah ok. Unfortunately these extra Laminar displays are not in the panel texture that the rest of the aircraft uses. They are rendered somewhere else using internal X-Plane code in a totally different way. I'm not sure why they are done differently, the default X-Plane CDU also works like this as well. Also the other problem is that even if you could access the texture, you wouldn't be able to interact with any of the buttons and knobs.

**Comment by airfightergr** [comment]
> Ah ok. Unfortunately these extra Laminar displays are not in the panel texture that the rest of the aircraft uses. They are rendered somewhere else using internal X-Plane code in a totally different way. I'm not sure why they are done differently, the default X-Plane CDU also works like this as well. Also the other problem is that even if you could access the texture, you wouldn't be able to interact with any of the buttons and knobs.

Laminar. from 11.00, added the `ATTR_cockpit_device` directive for their own devices, and they are planning "soon" to support 3rd party developers to do the same. Are you in Laminar's slack?
