### ISSUE TITLE
Default XP11 & XP12 C172 G1000 Not working

### ISSUE THREAD

**Issue by Pitj3** [waynepiekarski/XTextureExtractor#23]
On loading the G1000 version of the C172 it shows a white image and won't generate a png to reference the positions from.

This behaviour is the same in XP11 and XP12

**Comment by waynepiekarski** [comment]
If this is the G1000 that is provided by Laminar, that doesn't use the standard panel texture like all 3rd party aircraft, so it cannot be captured by XTE. So unfortunately it is not possible to support this.
