### ISSUE TITLE
HELP - Launch remote java client from the main machine.

### ISSUE THREAD

**Issue by CliffAgius** [waynepiekarski/XTextureExtractor#24]
Hi,

I was wondering is it possible for the main machine running XPLane to call the batch file on the remote machine so that it starts automatically when Xplane is loaded.  I have remote machines but they don't have keyboard and mouse etc so wanted to to autostart but not sure if XPlane or this awesome tool can do this.

**Comment by waynepiekarski** [comment]
Remote starting an executable is something controlled by Windows, and X-Plane / XTE don't have any mechanism to do this (which is a good thing for security reasons). On Windows, you should be able to create a shortcut to the RUN-XTE.BAT file and put it in to C:\Profiles\{User}\‌​AppData\Roaming\Micro‌​soft\Windows\Start Menu\Programs\Startu‌​p. You also need to get the Windows machine to auto-login. Now when you reboot, it should start up everything automatically.

**Comment by CliffAgius** [comment]
Thanks for the reply. I have it doing this but when I move the aircraft and XPlane reloads the XTE screens on the 2nd and 3rd PCs close and I have to connect a mouse to run the Bat files again. 

Trying to see if there was a way to automate this step so when XPlane has finished its reload the remote machines would run the bat files and reconnect or if XTE would stay open rather than close.

Amazing project thank you for sharing and supporting.

**Comment by waynepiekarski** [comment]
In DOS batch files, you should be able to put a GOTO in there to go back and restart the Java client again. It will restart itself forever after that.
