### ISSUE TITLE
pop out resize ability?

### ISSUE THREAD

**Issue by georgegohl888** [waynepiekarski/XTextureExtractor#5]
i tired the plugin om my actual sim not my desktop and the pop out function works but the panels are massive. The window can be resize but the panel within it stays huge. is this a bug or just not implemented yet? Also does it remember the window locations so I don't have to re drag it every time?

**Comment by georgegohl888** [comment]
when it first comes up the window is the right size but the panel behind it is massive and wont fit

**Comment by waynepiekarski** [comment]
If you click the "Sv" button in the UI, it will save the layout of all the windows and restore them when the aircraft is restarted.

Can you post a screenshot of what the problem is? Does it happen for all aircraft? Is there any situation where it works properly?

**Comment by georgegohl888** [comment]
it seems to work for other aircraft such as the 737 just not the a320 and its funny how its only when its popped out.

**Comment by waynepiekarski** [comment]
I have written some instructions in issue #4 so lets move discussion there.
