### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by fan5fll** [waynepiekarski/XTextureExtractor#7]
Can you please share a complete list of prerequisites, as well as a video of instructions for installation?

Thank you so much

**Comment by Altalus** [comment]
May I suggest you try to follow these instructions found in the main readme.md file ?

> You should extract the ZIP file and copy the Plugin-XTextureExtractor-x64-Release directory into your X-Plane 11\Resources\plugins directory.

Best regards,

**Comment by waynepiekarski** [comment]
I don't have time to prepare anything more detailed than the existing readme, but someone did make a video on YouTube a while ago: https://www.youtube.com/watch?v=QevuhD-JLZU

**Comment by waynepiekarski** [comment]
Recently, Russ Barlow also did a video about XTextureExtractor as well https://www.youtube.com/watch?v=ACR1K2dwpME hope this is helpful to you all.
