### ISSUE TITLE
P.180 Avanti II .tex file

### ISSUE THREAD

**Issue by airfightergr** [waynepiekarski/XTextureExtractor#9]
I'm the developer of the [P.180 Avanti II](http://forums.x-pilot.com/files/file/1081-p180-avanti-ii/) and I have attached a .tex file for my aircraft. Includes all displays of the aircraft and works fine!

Please feel free to include it in your plugin. Great idea and great work! Congrats!

[avanti.acf.tex.zip](https://github.com/waynepiekarski/XTextureExtractor/files/3419677/avanti.acf.tex.zip)

**Comment by waynepiekarski** [comment]
Thanks for the contribution! I have added this file to the next release.
